#____GENERAL____

prefix : data/revised_test/
restart : FALSE

#____SCAFFOLDS____

default_scaffold_parameters :
  sigmoid_aggression : 6
  n_cells : 1000
  gamma : 0.1
  max_depth : 3
  max_width : 2
  ptime_beta : 0.5
  ptime_alpha : 1.

scaffolds:
  scaffold0:
    seed : 2556
    state_compositions:
    - - 1
      - 0
      - 0
      - 0
    - - 0.5
      - 0.25
      - 0.125
      - 0.125
    - - 0.1
      - 0.1
      - 0.4
      - 0.4
    - - 0.25
      - 0.625
      - 0.0625
      - 0.0625
    - - 0
      - 0
      - 1
      - 0
    - - 0
      - 0
      - 0
      - 1
    - - 0
      - 1
      - 0
      - 0
    - - 0
      - 1
      - 0
      - 0
  scaffold1:
    seed : 2557
    state_compositions:
    - - 1
      - 0
      - 0
      - 0
    - - 0.5
      - 0.3
      - 0.1
      - 0.1
    - - 0.15000000000000002
      - 0.15000000000000002
      - 0.35
      - 0.35
    - - 0.275
      - 0.625
      - 0.05
      - 0.05
    - - 0.05
      - 0
      - 0.85
      - 0.1
    - - 0.05
      - 0
      - 0.1
      - 0.85
    - - 0.05
      - 0.95
      - 0
      - 0
    - - 0.05
      - 0.95
      - 0
      - 0
  scaffold2:
    seed : 2558
    state_compositions:
    - - 1
      - 0
      - 0
      - 0
    - - 0.5
      - 0.325
      - 0.0875
      - 0.0875
    - - 0.175
      - 0.175
      - 0.32499999999999996
      - 0.32499999999999996
    - - 0.2875
      - 0.625
      - 0.04375
      - 0.04375
    - - 0.075
      - 0
      - 0.775
      - 0.15
    - - 0.075
      - 0
      - 0.15
      - 0.775
    - - 0.075
      - 0.925
      - 0
      - 0
    - - 0.075
      - 0.925
      - 0
      - 0
  scaffold3:
    seed : 2559
    state_compositions:
    - - 1
      - 0
      - 0
      - 0
    - - 0.5
      - 0.35
      - 0.075
      - 0.075
    - - 0.2
      - 0.2
      - 0.30000000000000004
      - 0.30000000000000004
    - - 0.3
      - 0.625
      - 0.0375
      - 0.0375
    - - 0.1
      - 0
      - 0.7
      - 0.2
    - - 0.1
      - 0
      - 0.2
      - 0.7
    - - 0.1
      - 0.9
      - 0
      - 0
    - - 0.1
      - 0.9
      - 0
      - 0
  scaffold4:
    seed : 2560
    state_compositions:
    - - 1
      - 0
      - 0
      - 0
    - - 0.5
      - 0.375
      - 0.0625
      - 0.0625
    - - 0.225
      - 0.225
      - 0.275
      - 0.275
    - - 0.3125
      - 0.625
      - 0.03125
      - 0.03125
    - - 0.125
      - 0
      - 0.625
      - 0.25
    - - 0.125
      - 0
      - 0.25
      - 0.625
    - - 0.125
      - 0.875
      - 0
      - 0
    - - 0.125
      - 0.875
      - 0
      - 0

#____TESTS____

test_replicates : 1

default_test_parameters:
  datasets:
    - revised_rna.h5ad
    - revised_atac.h5ad
  feature_types:
    - RNA
    - ATAC
  n_jobs : 1
  pure_states: [C, A, B, D]
  cell_state_col : cell_groups
  rd_stds : [0.45, 0.33]

test_conditions:
  test3 : 
    rd_means : [1000, 3500]
  test4 : 
    rd_means : [2000, 7000]
  test5 : 
    rd_means : [4000, 14000]
