#____GENERAL____

prefix : 'data/hard'
restart  : TRUE

#____SCAFFOLDS____
default_scaffold_parameters:
  sigmoid_aggression : 6
  n_cells : 1000
  gamma : 0.1
  max_depth : 3
  max_width : 2
  ptime_beta : 0.5
  ptime_alpha : 1.

scaffolds:
  scaffold0:
    state_compositions:
    - - 1
      - 0
      - 0
      - 0
    - - 0.5
      - 0.25
      - 0.125
      - 0.125
    - - 0.1
      - 0.1
      - 0.4
      - 0.4
    - - 0.25
      - 0.625
      - 0.0625
      - 0.0625
    - - 0
      - 0
      - 1
      - 0
    - - 0
      - 0
      - 0
      - 1
    - - 0
      - 1
      - 0
      - 0
    - - 0
      - 1
      - 0
      - 0
  scaffold1:
    state_compositions:
    - - 1
      - 0
      - 0
      - 0
    - - 0.5
      - 0.3
      - 0.1
      - 0.1
    - - 0.15000000000000002
      - 0.15000000000000002
      - 0.35
      - 0.35
    - - 0.275
      - 0.625
      - 0.05
      - 0.05
    - - 0.05
      - 0
      - 0.85
      - 0.1
    - - 0.05
      - 0
      - 0.1
      - 0.85
    - - 0.05
      - 0.95
      - 0
      - 0
    - - 0.05
      - 0.95
      - 0
      - 0
  scaffold2:
    state_compositions:
    - - 1
      - 0
      - 0
      - 0
    - - 0.5
      - 0.325
      - 0.0875
      - 0.0875
    - - 0.175
      - 0.175
      - 0.32499999999999996
      - 0.32499999999999996
    - - 0.2875
      - 0.625
      - 0.04375
      - 0.04375
    - - 0.075
      - 0
      - 0.775
      - 0.15
    - - 0.075
      - 0
      - 0.15
      - 0.775
    - - 0.075
      - 0.925
      - 0
      - 0
    - - 0.075
      - 0.925
      - 0
      - 0
  scaffold3:
    state_compositions:
    - - 1
      - 0
      - 0
      - 0
    - - 0.5
      - 0.35
      - 0.075
      - 0.075
    - - 0.2
      - 0.2
      - 0.30000000000000004
      - 0.30000000000000004
    - - 0.3
      - 0.625
      - 0.0375
      - 0.0375
    - - 0.1
      - 0
      - 0.7
      - 0.2
    - - 0.1
      - 0
      - 0.2
      - 0.7
    - - 0.1
      - 0.9
      - 0
      - 0
    - - 0.1
      - 0.9
      - 0
      - 0
  scaffold4:
    state_compositions:
    - - 1
      - 0
      - 0
      - 0
    - - 0.5
      - 0.375
      - 0.0625
      - 0.0625
    - - 0.225
      - 0.225
      - 0.275
      - 0.275
    - - 0.3125
      - 0.625
      - 0.03125
      - 0.03125
    - - 0.125
      - 0
      - 0.625
      - 0.25
    - - 0.125
      - 0
      - 0.25
      - 0.625
    - - 0.125
      - 0.875
      - 0
      - 0
    - - 0.125
      - 0.875
      - 0
      - 0
  scaffold5:
    state_compositions:
    - - 1
      - 0
      - 0
      - 0
    - - 0.5
      - 0.4
      - 0.05
      - 0.05
    - - 0.25
      - 0.25
      - 0.24999999999999997
      - 0.24999999999999997
    - - 0.325
      - 0.625
      - 0.025
      - 0.025
    - - 0.15
      - 0
      - 0.55
      - 0.3
    - - 0.15
      - 0
      - 0.3
      - 0.55
    - - 0.15
      - 0.85
      - 0
      - 0
    - - 0.15
      - 0.85
      - 0
      - 0

#____TESTS____

test_replicates : 3

default_test_parameters:
  datasets:
    - ../frankencell/data/benchmark_rna.h5ad
    - ../frankencell/data/benchmark_atac.h5ad
  feature_types:
    - RNA
    - ATAC
  pure_states: [C, A, B, D]
  cell_state_col : cell_groups
  n_jobs : 5
  rd_stds : [0.45, 0.33]

test_conditions:
  test1 :
    rd_means : [313, 1000]
  test2 : 
    rd_means : [625, 2000]
  test3 : 
    rd_means : [1250, 4000]
  test4 : 
    rd_means : [2500, 8000]
  test5 : 
    rd_means : [5000, 16000]

#____PREPROCESSING____
default_preprocessing_parameters: 
  min_cells : 25

preprocessing:
  pca :
    script : pca-preprocess
    concurrent_job_penalty : 0
    parameters:
      min_dispersion : 0.7
      feature_type : RNA
  lsi :
    script : lsi-preprocess
    concurrent_job_penalty : 0
    parameters :
      feature_type : ATAC
  mira_monotonic :
    script : mira-preprocess
    concurrent_job_penalty : 1
    parameters:
      use_atac_features : TRUE
      min_dispersion : 0.7
      tune : TRUE
      kl_strategy : monotonic
  mira_cyclic : 
    script : mira-preprocess
    concurrent_job_penalty : 1
    parameters :
      use_atac_features : TRUE
      min_dispersion : 0.7
      tune : TRUE
      kl_strategy : cyclic

#____METHODS____
default_method_parameters: {}

methods :
  mira_tree :
    run_file : /Users/alynch/projects/multiomics/cellgen2/frankencell/methods/mira/run
    definition_file : /Users/alynch/projects/multiomics/cellgen2/frankencell/methods/mira/definition.yaml
    trials : 
      mira_cyclic_ATAC_log:
        parameters: use_rep="ATAC", box_cox=0
        preprocessing: mira_cyclic
      mira_cyclic_ATAC_sqrt:
        parameters: use_rep="ATAC", box_cox=0.5
        preprocessing: mira_cyclic
      mira_cyclic_RNA_log:
        parameters: use_rep="RNA", box_cox=0
        preprocessing: mira_cyclic
      mira_cyclic_RNA_sqrt:
        parameters: use_rep="RNA", box_cox=0.5
        preprocessing: mira_cyclic
      mira_cyclic_joint_log:
        parameters: use_rep="joint", box_cox=0
        preprocessing: mira_cyclic
      mira_cyclic_joint_sqrt:
        parameters: use_rep="joint", box_cox=0.5
        preprocessing: mira_cyclic
      mira_monotonic_ATAC_log:
        parameters: use_rep="ATAC", box_cox=0
        preprocessing: mira_monotonic
      mira_monotonic_ATAC_sqrt:
        parameters: use_rep="ATAC", box_cox=0.5
        preprocessing: mira_monotonic
      mira_monotonic_RNA_log:
        parameters: use_rep="RNA", box_cox=0
        preprocessing: mira_monotonic
      mira_monotonic_RNA_sqrt:
        parameters: use_rep="RNA", box_cox=0.5
        preprocessing: mira_monotonic
      mira_monotonic_joint_constrained_log:
        parameters: use_rep="joint_constrained", box_cox=0
        preprocessing: mira_monotonic
      mira_monotonic_joint_constrained_sqrt:
        parameters: use_rep="joint_constrained", box_cox=0.5
        preprocessing: mira_monotonic
      mira_monotonic_joint_log:
        parameters: use_rep="joint", box_cox=0
        preprocessing: mira_monotonic
      mira_monotonic_joint_sqrt:
        parameters: use_rep="joint", box_cox=0.5
        preprocessing: mira_monotonic
  slingshot_pca : 
    run_file : /Users/alynch/projects/multiomics/cellgen2/frankencell/methods/custom_slingshot/run.R
    definition_file : /Users/alynch/projects/multiomics/cellgen2/frankencell/methods/custom_slingshot/definition.yaml
    trials:
      min_dim_3:
        parameters: min_dim=3
        preprocessing: pca
      min_dim_4:
        parameters: min_dim=4
        preprocessing: pca
      min_dim_5:
        parameters: min_dim=5
        preprocessing: pca
  slingshot_lsi : 
    run_file : /Users/alynch/projects/multiomics/cellgen2/frankencell/methods/signac/run.R
    definition_file : /Users/alynch/projects/multiomics/cellgen2/frankencell/methods/signac/definition.yaml
    trials:
      allen_3_True:
        parameters: min_dim=3, style="allen", skip_first_dim=TRUE
        preprocessing: lsi
      allen_4_True:
        parameters: min_dim=4, style="allen", skip_first_dim=TRUE
        preprocessing: lsi
      allen_5_True:
        parameters: min_dim=5, style="allen", skip_first_dim=TRUE
        preprocessing: lsi
      seurat_3_True:
        parameters: min_dim=3, style="seurat", skip_first_dim=TRUE
        preprocessing: lsi
      seurat_4_True:
        parameters: min_dim=4, style="seurat", skip_first_dim=TRUE
        preprocessing: lsi
      seurat_5_True:
        parameters: min_dim=5, style="seurat", skip_first_dim=TRUE
        preprocessing: lsi
      signac_3_True:
        parameters: min_dim=3, style="signac", skip_first_dim=TRUE
        preprocessing: lsi
      signac_4_True:
        parameters: min_dim=4, style="signac", skip_first_dim=TRUE
        preprocessing: lsi
      signac_5_True:
        parameters: min_dim=5, style="signac", skip_first_dim=TRUE
        preprocessing: lsi